Ods 4482
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #1
Opened 2020-10-16 13:29 UTC by ptar-innive

2020-10-16 13:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker?pullRequest=1) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker?pullRequest=1) before we can accept your contribution.<br/><hr/>**Peter Tar** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker?pullRequest=1) it.</sub>

2020-10-16 15:17 UTC, jamessmckay requested changes

2020-10-16 15:17 UTC, jamessmckay commented on docker-compose-prod.yaml
> +version: '3.3'
lets use version 3.8 instead please for the compose files.

2020-10-16 15:17 UTC, jamessmckay commented on GateWay/Dockerfile
> +EXPOSE 80
should we even expose port 80?

2020-10-16 15:17 UTC, jamessmckay commented on GateWay/Dockerfile
> +RUN mkdir /etc/nginx/ssl
I think i makes sense to have a run command to update the os thoughts?

2020-10-16 15:17 UTC, jamessmckay commented on docker-compose-prod.yaml
> +      volumes:
i think we will need a volume for plugins, so that in the future we can push up plugins for the application. the app settings should point to the that mount

2020-10-16 15:17 UTC, jamessmckay commented on docker-compose-stage.yaml
> +version: '3.3'
we should be using 3.8 for the compose version please

2020-10-16 15:17 UTC, jamessmckay commented on docker-compose-prod.yaml
> +      - ${PWD}/PSQL-ODS/data:/var/lib/postgresql/data
what is your plan for the data volumes? will it be something like this?
```
version: '3.8'

services:
    pg12:
        image: postgres:12-alpine
        container_name: pg12
        volumes:
            - pg12-database:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=${PG_PASSWORD}
        restart: on-failure

    # pg11:
    #     image: postgres:11-alpine
    #     container_name: pg11
    #     volumes:
    #         - pg11-database:/var/lib/postgresql/data
    #     ports:
    #         - 5432:5432
    #     environment:
    #         - POSTGRES_PASSWORD=${PG_PASSWORD}
    #     restart: on-failure

#    mssql2017:
#        image: mcr.microsoft.com/mssql/server:latest
#        container_name: mssql2017
#        volumes:
#            - mssql2017-database:/var/opt/mssql
#        ports:
#            - 1432:1433
#        environment:
#            - ACCEPT_EULA=Y
#            - SA_PASSWORD=${MSSQL_PASSWORD}
#            - MSSQL_PID=Developer
#        restart: on-failure

volumes:
    pg12-database:
        driver: local
        name: pg12-database

    # pg11-database:
    #     driver: local
    #     name: pg11-database

#    mssql2017-database:
#        driver: local
#        name: mssql2017-database
```

2020-10-16 15:20 UTC, vimayya commented on GateWay/Dockerfile
> +LABEL maintainer="EdFi Innive"
Can you change this to Ed-Fi Alliance ? Ed-Fi Alliance and the community will be the long term maintainer of this source code. Add CONTRIBUTORS.md file to recognize Google and Innvie

2020-10-16 15:23 UTC, ptar-innive commented on GateWay/Dockerfile
> +EXPOSE 80
yes, need port 80 to redirect to 443 :)

2020-10-16 15:24 UTC, ptar-innive commented on docker-compose-prod.yaml
> +      - ${PWD}/PSQL-ODS/data:/var/lib/postgresql/data
volumes are using the default driver, and the path is directly passed, so no-one has to search for where the docker put the volumes, but the volumes will be in that path where the code is

2020-10-16 15:25 UTC, ptar-innive commented on GateWay/Dockerfile
> +LABEL maintainer="EdFi Innive"
do you have some contact email for that, so i can pass it too?

2020-10-16 15:26 UTC, stephenfuqua commented on GateWay/Dockerfile
> +LABEL maintainer="EdFi Innive"
techsupport@ed-fi.org.

I can create a separate pull request with the contributors and notices files.

2020-10-18 01:30 UTC, jamessmckay commented on GateWay/Dockerfile
> +LABEL maintainer="EdFi Innive"
`Ed-Fi Alliance, LLC and Contributors` is what we have for the ODS, should we use the same? @vimayya

2020-10-18 19:04 UTC, vimayya commented on GateWay/Dockerfile
> +LABEL maintainer="EdFi Innive"
If it needs to be in the email format techsupport@ed-fi.org is good. Otherwise use 'Ed-Fi Alliance, LLC and Contributors'

2020-10-19 12:07 UTC, ptar-innive commented on GateWay/Dockerfile
> +RUN mkdir /etc/nginx/ssl
sidenote: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run , but adding it, as the build processes are running as root

2020-10-19 12:22 UTC, ptar-innive commented on docker-compose-prod.yaml
> +version: '3.3'
changed

2020-10-19 12:23 UTC, ptar-innive commented on docker-compose-stage.yaml
> +version: '3.3'
changed

2020-10-19 12:23 UTC, ptar-innive commented on GateWay/Dockerfile
> +LABEL maintainer="EdFi Innive"
changed

2020-10-19 12:23 UTC, ptar-innive commented on docker-compose-prod.yaml
> +      volumes:
plugins are not version controlled?

2020-10-19 12:40 UTC, jamessmckay commented on docker-compose-prod.yaml
> +      volumes:
they are and will be installed via nuget

2020-10-19 12:47 UTC, ptar-innive commented on docker-compose-prod.yaml
> +      volumes:
what should be the folder?

2020-10-19 12:57 UTC, blmeyers reviewed
Leaving as comments, several of these may be handled with future tickets but wanted to make sure the concerns were raised.

2020-10-19 12:57 UTC, blmeyers commented on GateWay/edfi.conf
> +     location /webapi {
This would probably be handled by a separate ticket, but how are we handling CORS configuration for this setup?

2020-10-19 12:57 UTC, blmeyers commented on GateWay/edfi.conf
> +          proxy_set_header   Host $host;
The internal systems are also expecting "X-Forwarded-Host" and "X-Forwarded-Port" headers for reverse proxy support.  Both are used in order to build accurate absolute urls (such as for Open Api Metadata specification).  Also may be another ticket, but the API has to be told its running in reverse proxy mode or it won't trust reverse proxy headers, so that will need to be handled through config.  That one we may want to just explicitly set it using an environment variable or user-secret (highest priority) so the appsettings.json value will be ignored, since this isn't actually something the user should configure in this environment.  That would avoid the user putting the system in an invalid state.

2020-10-19 12:57 UTC, blmeyers commented on GateWay/edfi.conf
> +     location /webapi {
This is using virtual paths for routing, but the underlying systems won't support this.  See currently open ticket https://tracker.ed-fi.org/browse/ODS-4594, for adding support for handling a virtual path on the reverse proxy.

2020-10-19 12:57 UTC, blmeyers commented on GateWay/edfi.conf
> +        root /usr/share/nginx/html;
We'll get dinged on security audit for this, shouldn't be exposing the default html anywhere.

2020-10-19 12:57 UTC, blmeyers commented on GateWay/edfi.conf
> +     location /webapi {
Is this allowing http connections from the client to talk to the internal servers?  Wouldn't this normally be a redirect to https?

2020-10-19 21:32 UTC, jamessmckay requested changes

2020-10-19 21:32 UTC, jamessmckay commented on GateWay/Dockerfile
> +CMD ["nginx", "-g", "daemon off;"]
why are we not running nginx as a deamon?

2020-10-19 21:32 UTC, jamessmckay commented on GateWay/edfi.conf
> +        root /usr/share/nginx/html;
agreed

2020-10-19 21:32 UTC, jamessmckay commented on docker-compose-prod.yaml
> +      - ${PWD}/PSQL-ODS/data:/var/lib/postgresql/data
???

2020-10-19 21:32 UTC, jamessmckay commented on docker-compose-prod.yaml
> +      volumes:
mount the folder name as /mnt/plugins

2020-10-20 07:38 UTC, ptar-innive commented on GateWay/Dockerfile
> +CMD ["nginx", "-g", "daemon off;"]
in docker the general concept is to log to output, which means it should not run as a daemon. If you run a process in docker as a daemon, when the startup process exits with forking the daemon process in the background, the docker daemon will stop the container, as the startup process exited, treating as nothing running in the container, that is why it is a general concept to run everything in foreground

2020-10-20 07:42 UTC, ptar-innive commented on docker-compose-prod.yaml
> +      - ${PWD}/PSQL-ODS/data:/var/lib/postgresql/data
what is the question? in the compose file volume section is the host folder path, on the right side is the path to mount inside the container

2020-10-20 07:46 UTC, ptar-innive commented on GateWay/edfi.conf
> +     location /webapi {
it would be ideal to use path based routing, as in that way don't have to bother with domain names and domain setups and multiple ssls in the scenario, so yes, it will be path based routed.

2020-10-20 08:33 UTC, ptar-innive commented on docker-compose-prod.yaml
> +      volumes:
added

2020-10-20 08:39 UTC, ptar-innive commented on GateWay/edfi.conf
> +     location /webapi {
redirected all http traffic to https

2020-10-20 08:42 UTC, ptar-innive commented on GateWay/edfi.conf
> +        root /usr/share/nginx/html;
set to 404

2020-10-20 08:50 UTC, ptar-innive commented on GateWay/edfi.conf
> +          proxy_set_header   Host $host;
added

2020-10-20 08:57 UTC, ptar-innive commented on GateWay/edfi.conf
> +     location /webapi {
added some CORS related headers, but that should be revised when the system starts up

2020-10-20 16:59 UTC, jamessmckay approved these changes

2020-10-20 16:59 UTC, merged