[Ods-4521] - docker-compose setup
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #10
Opened 2020-10-28 18:16 UTC by ptar-innive

2020-11-09 19:40 UTC, blmeyers requested changes

2020-11-09 20:02 UTC, jamessmckay commented on DB-Admin/init-database.sh
> +psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
done

2020-11-09 20:02 UTC, jamessmckay commented on DB-ODS/init-database.sh
> +psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
done

2020-11-09 20:02 UTC, jamessmckay commented on DB-ODS/init-database.sh
> +    CREATE DATABASE "EdFi_ODS" TEMPLATE 'EdFi_Ods_Minimal_Template';
done

2020-11-09 20:04 UTC, jamessmckay commented on DB-ODS/init-database.sh
> +    CREATE DATABASE "EdFi_Ods_Populated_Template" TEMPLATE template0;
initially the intent is to run sandbox as a "production" environment so I modified the script to support both a shared instance and sandbox env.

2020-11-09 20:05 UTC, jamessmckay commented on DB-Sandbox/EdFi_Admin.sql
> +--
currently we do not ahve a build that creates sandbox and security as pg dumps. This was generated using the cloud build.

2020-11-09 20:13 UTC, jamessmckay commented on DB-Sandbox/EdFi_Admin.sql
> +--
ODS-4677

2020-11-09 20:13 UTC, jamessmckay commented on DB-Sandbox/EdFi_Security.sql
> +--
ODS-4677

2020-11-09 20:24 UTC, jamessmckay commented on DB-Sandbox/init-database.sh
> +    GRANT ALL PRIVILEGES ON DATABASE "EdFi_Ods_Populated_Template" TO postgres;
done

2020-11-09 20:26 UTC, jamessmckay commented on Web-GateWay/Dockerfile
> +# SPDX-License-Identifier: Apache-2.0
ODS-4679

2020-11-09 20:27 UTC, jamessmckay commented on DB-Admin/EdFi_Admin.sql
> -    AS $$
probably due to change of me removing cr-lf, to lf. I will be replacing the files with the windows version, and adding a gitattributes file.

2020-11-09 20:38 UTC, jamessmckay commented on DB-Admin/Dockerfile
> +FROM postgres:11-alpine
fixed, and updated the docker files to use the fixed scripts. created new tickets to have admin and security dbs created as nuget packages

2020-11-09 20:39 UTC, jamessmckay commented on Web-GateWay/edfi-prod.conf
> +upstream webapi {
(y)

2020-11-09 20:40 UTC, jamessmckay commented on Web-GateWay/edfi-stage.conf
>  }
this should be for a reverse proxy implementation

2020-11-09 20:46 UTC, jamessmckay commented on Web-GateWay/nginx.conf
> +        listen       5001;
deferring until we get reverse proxy fully working. ODS-4675

2020-11-09 20:47 UTC, jamessmckay commented on Web-Sandbox-Admin/sandbox.appsettings.json
> +  "UseReverseProxyHeaders": false,
agreed ODS-4595

2020-11-10 15:27 UTC, blmeyers commented on DB-ODS/init-database.sh
> +    CREATE DATABASE "EdFi_Ods_Populated_Template" TEMPLATE template0;
We can address for the production implementation, but I think we're going to need specialized scripts, one for shared, one for sandbox, one for year specific.  We don't want to set up extra databases unless we have to.

2020-11-10 19:16 UTC, blmeyers approved these changes

2020-11-10 19:17 UTC, merged