Expand coverage for disabling PGBouncer in favor of client-side pooling
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #122
Opened 2022-09-12 17:37 UTC by gmcelhanon

2022-09-12 18:01 UTC, vimayya commented on README.md
> +5. Apply connection string settings for [client-side connection pooling](https://www.npgsql.org/doc/connection-string-parameters.html?q=pooling#pooling) in the _appsettings.template.json_ files for t
While modifying appsettings.template.json, official images can't be used, is there a way to pass in as env variable but have a separate pool size for admin app and api?

2022-09-12 18:08 UTC, gmcelhanon commented on README.md
> +5. Apply connection string settings for [client-side connection pooling](https://www.npgsql.org/doc/connection-string-parameters.html?q=pooling#pooling) in the _appsettings.template.json_ files for t
Yes, and I have a branch that I started when working on this ticket with exactly that sort of approach, which we'd need to continue development on. We'd just need separate environment variables for the Admin's ODS pool size and the ODS API's ODS pool size.

2022-09-21 14:28 UTC, vimayya commented on .env.example
> +# PostgreSQL client-side pooling (see repository README file for additional information)
```suggestion
# PostgreSQL client-side pooling. Consider only if not using PgBouncer (see repository README file for additional information)
```

2022-09-21 14:49 UTC, vimayya commented
@gmcelhanon Code changes and readme looks good to me. I haven't done any testing.

2022-09-22 14:39 UTC, AxelMarquez requested changes
The containers don't pick up the new env var values set up in the .env file since the compose files don't forward them yet. For example, if I set `NPG_POOLING_ENABLED=true` in the .env file it doesn't get applied in the container.

To do so, add each env var to the environment section in the image definition in the compose files.

2022-09-22 21:03 UTC, AxelMarquez approved these changes

2022-09-22 21:03 UTC, merged