[ODS-5999]Added MultiTenant example and updated ods-api-web-gateway image
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #165
Opened 2023-09-21 19:31 UTC by semalaiappan

2023-09-22 21:55 UTC, simpat-jesus requested changes

2023-09-22 21:55 UTC, simpat-jesus commented on Compose/mssql/compose-multi-tenant-env.yml
> +    volumes:
Docker-Compose will be generating this example, and currently we have only pgsql examples generated; so this example can be removed

2023-09-22 21:55 UTC, simpat-jesus commented on Compose/pgsql/MultiTenant/appsettings.docker.json
> +    "Features": [
Features is an array, to avoid overriding any value, use     "Features:11:Enabled" = true 
to enable MultiTenant feature

2023-09-22 21:55 UTC, simpat-jesus commented on Compose/pgsql/MultiTenant/bootstrap.sh
> +#!/bin/sh
#! should be added at the beginning of the file

2023-09-22 21:55 UTC, simpat-jesus commented on Compose/pgsql/compose-multi-tenant-env.yml
> +# SPDX-License-Identifier: Apache-2.0
this file can be removed, and leave only the compose inside MultiTenant folder

2023-09-22 21:55 UTC, simpat-jesus commented on multi-tenant-env-up.ps1
> +if ($Engine -eq 'PostgreSQL') {
Since we are only adding a pgsql example, this can be removed and default to pgsql

2023-09-22 21:55 UTC, simpat-jesus commented on multi-tenant-env-clean.ps1
> +if ($Engine -eq 'PostgreSQL') {
Since we are only adding a pgsql example, this can be removed and default to pgsql

2023-09-22 21:55 UTC, simpat-jesus commented on Compose/pgsql/MultiTenant/compose-multi-tenant-env.yml
> +      ODS_POSTGRES_HOST: pb-ods-tenant1
This can be removed, the ODS host is provided by the OdsInstances table in admin database

2023-09-22 21:55 UTC, simpat-jesus commented on Compose/pgsql/MultiTenant/compose-multi-tenant-env.yml
> +    image: bitnami/pgbouncer
use tag 1.20.0 for bitnami/pgbouncer images

2023-09-22 23:27 UTC, simpat-jesus commented on Compose/pgsql/MultiTenant/bootstrap.sh
> +EDFI_ODS_CONNECTION_STRING="host=$ODS_POSTGRES_HOST;port=$ODS_PGBOUNCER_PORT;username=$POSTGRES_USER;password=$POSTGRES_PASSWORD;database=EdFi_Ods;application name=EdFi.Ods.WebApi;"
Add pooling=${NPG_POOLING_ENABLED};minimum pool size=10;maximum pool size=${NPG_API_MAX_POOL_SIZE_ODS}; to the connection string

2023-09-25 03:18 UTC, semalaiappan commented on Compose/pgsql/MultiTenant/compose-multi-tenant-env.yml
> +      ODS_POSTGRES_HOST: pb-ods-tenant1
ODS_POSTGRES_HOST needed in bootstrap.sh to pass it here EDFI_ODS_CONNECTION_STRING="host=$ODS_POSTGRES_HOST;port=$ODS_PGBOUNCER_PORT;username=$POSTGRES_USER;password=$POSTGRES_PASSWORD;database=EdFi_Ods;application name=EdFi.Ods.WebApi;"

2023-09-25 04:17 UTC, semalaiappan commented on Compose/mssql/compose-multi-tenant-env.yml
> +    volumes:
Removed it . Thanks

2023-09-25 04:17 UTC, semalaiappan commented on Compose/pgsql/MultiTenant/bootstrap.sh
> +#!/bin/sh
Fixed it . Thanks

2023-09-25 04:18 UTC, semalaiappan commented on Compose/pgsql/compose-multi-tenant-env.yml
> +# SPDX-License-Identifier: Apache-2.0
Fixed it . Thanks

2023-09-25 04:18 UTC, semalaiappan commented on multi-tenant-env-up.ps1
> +if ($Engine -eq 'PostgreSQL') {
Fixed it . Thanks

2023-09-25 04:18 UTC, semalaiappan commented on multi-tenant-env-clean.ps1
> +if ($Engine -eq 'PostgreSQL') {
Fixed it . Thanks

2023-09-25 04:18 UTC, semalaiappan commented on Compose/pgsql/MultiTenant/compose-multi-tenant-env.yml
> +    image: bitnami/pgbouncer
Fixed it . Thanks

2023-09-25 04:18 UTC, semalaiappan commented on Compose/pgsql/MultiTenant/bootstrap.sh
> +EDFI_ODS_CONNECTION_STRING="host=$ODS_POSTGRES_HOST;port=$ODS_PGBOUNCER_PORT;username=$POSTGRES_USER;password=$POSTGRES_PASSWORD;database=EdFi_Ods;application name=EdFi.Ods.WebApi;"
Fixed it . Thanks

2023-09-25 16:06 UTC, semalaiappan commented
@simpat-jesus  Ready for review again

2023-09-26 19:45 UTC, simpat-jesus approved these changes

2023-09-26 19:45 UTC, merged