[ADMINAPI-347] Update references from Admin App to Admin API in Docker Deployment
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #167
Opened 2023-09-26 18:53 UTC by CSR2017

@vimayya @jagudelo-gap
Please help review and merge the changes.
Thanks

2023-09-26 22:12 UTC, jagudelo-gap requested changes

2023-09-26 22:12 UTC, jagudelo-gap commented on Web-Gateway/Alpine/Dockerfile
> +ENV ADMIN_API_VIRTUAL_NAME=adminapi
@CSR2017 
Please, update the Web-Gateway\Alpine\README.md file to include this new env variable

2023-09-27 15:52 UTC, simpat-jesus commented on Web-Gateway/Alpine/default.conf.template
> +        proxy_pass http://${ADMIN_API_VIRTUAL_NAME};
this will prevent the container to start up if users don't set up admin appi (i.ex. if they use admin app instead of admin api)

tho get the container up and running, replace with
`resolver localhost;
set $path ${ADMIN_API_VIRTUAL_NAME};
proxy_pass http://$path;`

With this, if users navigate to http://$path they will get an error instead of preventing the container to start up correctly

2023-09-27 19:41 UTC, jagudelo-gap approved these changes

2023-09-29 20:20 UTC, vimayya commented
I created https://tracker.ed-fi.org/browse/ADMINAPI-748 based on the changes in the PR, I don't think that should block merging this PR though.

2023-09-29 20:21 UTC, vimayya approved these changes

2023-10-03 15:56 UTC, merged