[ODS-6000] Add MultiTenant with context routes example
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #169
Opened 2023-09-28 22:27 UTC by semalaiappan

2023-09-28 22:30 UTC, semalaiappan commented
docker build --pull --rm -f Compose-Generator/Alpine/Dockerfile -t edfiodsdocker:latest Compose-Generator/Alpine

docker run --rm -v C:/OSS-Workspace/Ed-Fi-ODS-Docker/Compose-Generator/Alpine/templates/pgsql/MultiTenant-OdsContext/parameters.example.yml:/parameters -v C:/OSS-Workspace/Ed-Fi-ODS-Docker/Compose/pgsql/MultiTenant-OdsContext:/output edfiodsdocker:latest MultiTenant-OdsContext.sh

 .\multi-tenant-odscontexts-clean.ps1   

.\multi-tenant-odscontexts-up.ps1

2023-09-29 20:55 UTC, simpat-jesus requested changes
Some minor changes

2023-09-29 20:55 UTC, simpat-jesus commented on Compose-Generator/Alpine/Dockerfile
> +RUN apk --no-cache add dos2unix=~7
I tested without this line and it worked fine, Alpine 3.18.3 image already has dos2unix installed

2023-09-29 20:55 UTC, simpat-jesus commented on Compose-Generator/Alpine/templates/pgsql/MultiTenant-OdsContext/run.sh
> +chmod 777 /output/bootstrap.sh
use chmod 755, also add both dos2unix and chmod to Multitenant and SingleTenant-OdsContext run.sh scripts

2023-09-29 20:55 UTC, simpat-jesus commented on Compose-Generator/Alpine/templates/pgsql/MultiTenant-OdsContext/compose-template.mustache
> +
Not a breaking issue, but we can format the template to only have empty spaces before a {{/ }} line

2023-09-29 22:03 UTC, semalaiappan commented on Compose-Generator/Alpine/Dockerfile
> +RUN apk --no-cache add dos2unix=~7
Removed it . Thanks

2023-09-29 22:03 UTC, semalaiappan commented on Compose-Generator/Alpine/templates/pgsql/MultiTenant-OdsContext/run.sh
> +chmod 777 /output/bootstrap.sh
Updated it . Thanks

2023-09-29 22:04 UTC, semalaiappan commented on Compose-Generator/Alpine/templates/pgsql/MultiTenant-OdsContext/compose-template.mustache
> +
Formatted it . Thanks

2023-09-29 22:27 UTC, simpat-jesus approved these changes

2023-09-29 22:28 UTC, merged