[ADMINAPI-970] Extend Docker Deployment for Admin API 2.1
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #178
Opened 2024-01-19 21:10 UTC by CSR2017

2024-01-22 21:44 UTC, jagudelo-gap reviewed
@CSR2017 
Please include Admin API in the README files

- Compose\pgsql\README.md
- Compose\pgsql\MultiTenant\README.md
- Compose\pgsql\MultiTenant-OdsContext\README.md

2024-01-23 22:44 UTC, simpat-jesus requested changes
Please modify the image for Admin Db containers for MultiTenant and MultiTenant with OdsContexts to be ${ADMIN_DB_IMAGE:-edfialliance/ods-api-db-admin:${TAG}}

Also, enable AllowRegistration and Swager; since this are just examples, users should be able to run the examples without modifying the compose files.

2024-01-24 17:57 UTC, simpat-jesus requested changes

2024-01-24 17:57 UTC, simpat-jesus commented on Compose-Generator/Alpine/templates/pgsql/MultiTenant-OdsContext/compose-template.mustache
> +      image: edfialliance/ods-admin-api:${ADMINAPI_TAG}
Indentation has two levels and should have only 1 level. Please verify the changes here match the generated files using the Compose-Generator

2024-01-24 17:57 UTC, simpat-jesus commented on Compose-Generator/Alpine/templates/pgsql/MultiTenant/compose-template.mustache
> +      ADMIN_API_VIRTUAL_NAME: "${ADMIN_API_VIRTUAL_NAME:-adminapi}"
There is a space at the end; this does not match the generated file. Please verify the changes here match the generated files using the Compose-Generator

2024-01-24 17:57 UTC, simpat-jesus commented on Compose-Generator/Alpine/templates/pgsql/MultiTenant/compose-template.mustache
> +      image: edfialliance/ods-admin-api:${ADMINAPI_TAG}
Indentation has two levels and should have only 1 level. Please verify the changes here match the generated files using the Compose-Generator

2024-01-25 15:41 UTC, jagudelo-gap approved these changes

2024-01-25 17:09 UTC, simpat-jesus approved these changes

2024-01-25 17:10 UTC, merged