[ODS-6178] Updates for ODS/API v6.2
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #180
Opened 2024-03-12 20:58 UTC by stephenfuqua

2024-03-12 23:24 UTC, andonyns requested changes

2024-03-12 23:24 UTC, andonyns commented on Web-Ods-AdminApp/Alpine/pgsql/Dockerfile
> +RUN apk --no-cache postgresql13-client=~13 jq=~1
```suggestion
RUN apk add --no-cache postgresql13-client=~13 jq=~1
```

2024-03-12 23:24 UTC, andonyns commented on Web-Ods-AdminApp/Alpine/pgsql/Dockerfile
> +RUN apk --no-cache postgresql13-client=~13 jq=~1
After this suggestion is applied, it's ready to merge

2024-03-13 14:00 UTC, stephenfuqua commented on Web-Ods-AdminApp/Alpine/pgsql/Dockerfile
> +RUN apk --no-cache postgresql13-client=~13 jq=~1
Did Admin App actually work? It is still programmed on .NET 6 or maybe even .NET 3.1 (I haven't looked), so I am curious what happens when we try to run it in a container that has .NET 8.

2024-03-13 14:01 UTC, stephenfuqua commented on Web-Ods-AdminApp/Alpine/pgsql/Dockerfile
> +RUN apk --no-cache postgresql13-client=~13 jq=~1
Done

2024-03-13 14:33 UTC, andonyns approved these changes

2024-03-13 14:33 UTC, merged