ODS-4477 WebApi Dockerfile
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #3
Opened 2020-10-21 13:39 UTC by ptar-innive

2020-10-21 13:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker?pullRequest=3) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker?pullRequest=3) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: ptar-innive<br/>:x: smundheinnive<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker?pullRequest=3) it.</sub>

2020-10-21 21:13 UTC, jamessmckay requested changes
I would like to sidebar this ticket in the morning.

2020-10-21 21:13 UTC, jamessmckay commented on WebApi/Dockerfile
> +ENTRYPOINT ["dotnet","EdFi.Ods.WebApi.exe"]
we also need to pass in an environment as a command line arguemnt for the application for example we do this by adding:
`--environment Production` for the production environment (Development for the development environment).

2020-10-22 11:13 UTC, ptar-innive commented on WebApi/Dockerfile
> +ENV VERSION="5.1.0-b12868"
i would not suggest it, during running the container there is no sense of it, as the code is there in the container, during build time this env variable is a clear indication of which version of software is running in the container, if you can modify it without commit, then how would you know what version was build? Images should be atomic

2020-10-22 11:13 UTC, ptar-innive commented on WebApi/Dockerfile
> +RUN wget -O /app/WebApi.zip https://www.myget.org/F/ed-fi/api/v2/package/EdFi.Suite3.Ods.WebApi/${VERSION} && unzip /app/WebApi.zip -d /app && rm -f /app/WebApi.zip
is not that come from application.json which is a volume file?

2020-10-22 11:20 UTC, ptar-innive commented on WebApi/Dockerfile
> +ENTRYPOINT ["dotnet","EdFi.Ods.WebApi.exe"]
how many such startup options should we handle? do it have documentation about it? Does it came from application.json?

2020-10-22 20:30 UTC, jamessmckay approved these changes

2020-10-22 20:31 UTC, merged