[ODS-4594] Support for different virtual path with Reverse Proxy
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #31
Opened 2020-12-07 16:08 UTC by tnunnerydl

2020-12-08 21:53 UTC, blmeyers requested changes

2020-12-08 21:53 UTC, blmeyers commented on Web-Gateway-Sandbox/Dockerfile
>  EXPOSE "5000"
This change should also stop exposing port 5000.

2020-12-08 21:53 UTC, blmeyers commented on Web-Gateway-Sandbox/nginx.conf
> +        listen       443 ssl;
We seem to have lost our support for listening on 80 for http and redirecting to https.  Probably need a new ticket to handle that?  The gateway should allow connections on regular http and redirect them to https, otherwise you just get failures using http.

2020-12-08 21:53 UTC, blmeyers commented on Web-Gateway-Sandbox/nginx.conf
> +        location /odsapi {
@vimayya Can you confirm what we want these paths as?  It would be nice to have some consistency with the paths, container paths, and staging/demo paths.  Staging and demo currently use /api, /docs, and /admin for the three sites.  The internal containers seem to be using api, swagger, and admin.  Does it make sense to align everything to match Staging/Demo?

2020-12-08 21:53 UTC, blmeyers commented on Web-Gateway-Sandbox/nginx.conf
>      server {
Shouldn't swagger also be hosted under the main port?

2020-12-08 21:53 UTC, blmeyers commented on Web-Ods-Api/appsettings.template.json
> +    "VirtualPathEnabled": true,
This should explicitly set a virtual path, not rely on defaults to match up with the nginx config.

2020-12-08 21:53 UTC, blmeyers commented on Web-Sandbox-Admin/appsettings.template.json
> +  "VirtualPathEnabled": true,
This should explicitly set a virtual path, not rely on defaults to match up with the nginx config.

2020-12-08 21:53 UTC, blmeyers commented on compose-shared-instance-env.yml
> +       - "5000:5000"
This should only be port 443.

2020-12-08 21:53 UTC, blmeyers commented on Web-Sandbox-Admin/appsettings.template.json
>    "OAuthUrl": "https://localhost:5001/oauth/",
This url needs to be updated too.

2020-12-08 21:53 UTC, blmeyers commented on Web-Ods-Api/Dockerfile
> +
```suggestion
```

2020-12-11 19:30 UTC, blmeyers requested changes

2020-12-11 19:30 UTC, blmeyers commented on Web-Sandbox-Admin/appsettings.template.json
> +  "PathBase": "/odsapi",
Wrong pathbase here?  Shouldn't this match the nginx config for sandbox admin?

2020-12-11 19:30 UTC, blmeyers commented on compose-sandbox-env-build.yml
>         - "5000:5000"
This shouldn't be exposing 5000 anymore.

2020-12-11 19:30 UTC, blmeyers commented on compose-sandbox-env.yml
>         - "5000:5000"
This shouldn't be exposing 5000 anymore.

2020-12-11 19:32 UTC, vimayya commented on Web-Gateway-Sandbox/nginx.conf
> +        location /odsapi {
@blmeyers would prefer to align with the staging and demo and change swagger to docs

2021-03-05 14:58 UTC, jamessmckay commented on Web-Gateway-Sandbox/nginx.conf
> +        listen       443 ssl;
ODS-4860

2021-03-05 15:04 UTC, jamessmckay commented on Web-Gateway-Sandbox/nginx.conf
> +        location /odsapi {
Note the swagger path does not work on docs at this point. I created a ticket to address this: ODS-4861

2021-03-06 01:18 UTC, blmeyers approved these changes

2021-03-06 01:18 UTC, merged