[AA-1185] Add AdminApp docker setup files
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #33
Opened 2020-12-14 23:35 UTC by CSR2017

@jamessmckay @vimayya @stephenfuqua 
Please help review and merge the changes.
Changes:
1. Added admin app specific docker, appsettings, run.sh and log4net config file.
2. Updated compose-shared-instance-env-build.yml file to include admin app. compose-shared-instance-env.yml file will be updated once the docker image is available on docker hub.
3. Updated nginx config to include admin app server entry
4. Read-me file will be updated with image link details once the docker image is available on docker hub.
Thanks

2020-12-15 13:58 UTC, stephenfuqua reviewed
I have a few small requests after this initial review. Now I'll run some testing on this.

2020-12-15 13:58 UTC, stephenfuqua commented on Web-Ods-AdminApp/Dockerfile
> +ENV VERSION="2.1.0-pre0003"
@jamessmckay was there any discussion about having the package version be driven by external environment variable instead of being embedded in the Dockerfile? Having a hard-coded version number here seems like it would get tedious.

2020-12-15 13:58 UTC, stephenfuqua commented on Web-Ods-AdminApp/README.md
> +
Can you remove the extra blank lines, so that there is just one empty line around each header and text block?

2020-12-15 13:58 UTC, stephenfuqua commented on Web-Ods-AdminApp/README.md
> +## Image Variants
On the other hand, this and other headings should have a line break below it. "Prefer spacing after # and newlines before and after" [source](https://google.github.io/styleguide/docguide/style.html#add-spacing-to-headings)

2020-12-15 13:58 UTC, stephenfuqua commented on Web-Ods-AdminApp/README.md
> +
Please remove two extra lines.

2020-12-15 13:58 UTC, stephenfuqua commented on Web-Ods-AdminApp/README.md
> +As for any pre-built image usage, it is the image user's responsibility to ensure that any use of this image complies with any relevant licenses for all software contained within.
For better readability, can you insert a hard-wrap in this? Two VS Code extensions that I find very useful for the line spacing and text wrapping are:

1. `markdownlint`
2. `rewrap`

2020-12-15 14:28 UTC, stephenfuqua commented on Web-Ods-AdminApp/Dockerfile
> +ENV VERSION="2.1.0-pre0003"
Looking at one example from elsewhere right now: https://github.com/dotnet/dotnet-docker/blob/master/src/aspnet/3.1/

Given that the Dockerfile may need to change from one version to the next, it does seem reasonable to have 2.1.0 in here. However, at a later date we may need to start creating separate folders to hold version-specific Dockerfiles.

Still, it is annoying that the pre-release version is embedded in here. For this pull request I think it is the right thing to do. But longer term I hope we can explore alternatives.

2020-12-15 14:52 UTC, stephenfuqua commented on Web-Ods-AdminApp/Dockerfile
> +ENV VERSION="2.1.0-pre0003"
I'm just going to create a separate spike ticket to explore this question. I think we could hack something together with creative use of `dotnet` CLI.

2020-12-15 15:00 UTC, jamessmckay requested changes
Note changes are needed for the other shared instance compose file. `compose-shared-instance-env.yml`

2020-12-15 15:01 UTC, jamessmckay commented
Note I have turned on the build for this image in docker hub. I will test after my retro this morning.

2020-12-15 15:02 UTC, jamessmckay commented on Web-Ods-AdminApp/README.md
> +As for any pre-built image usage, it is the image user's responsibility to ensure that any use of this image complies with any relevant licenses for all software contained within.
Please add these as dependencies in the visual studio code files.

2020-12-15 15:13 UTC, vimayya commented on Web-Ods-AdminApp/appsettings.template.json
> +      "ProductionApiUrl": "https://localhost:5001",
> Note will need a ticket for the changes coming in on ODS-4594 (Reverse Proxy) so this gets updated correctly
ODST-160

2020-12-15 15:16 UTC, vimayya commented on .env.example
> +ADMINAPP_BULKUPLOAD_FOLDER=<path to store admin app bulk upload hash cache files>
@CSR2017 Is this a setting that user would care about? do you see the user needing to change/access it ? If not may be it doesn't need to be in the env file.

2020-12-15 15:21 UTC, stephenfuqua commented on .env.example
> +ADMINAPP_BULKUPLOAD_FOLDER=<path to store admin app bulk upload hash cache files>
FYI, Suganya and I discussed it yesterday and agreed about using it for now. This setting helps avoid re-processing files. If we don't put it on a persistent volume then we lose the benefit of this feature in Admin App. However, I'm going to create a ticket today to log that information into the database instead of storing it in the filesystem. So I'm hoping we get rid of this before the release of Docker support for Admin App.

2020-12-15 15:22 UTC, stephenfuqua commented
> Note I have turned on the build for this image in docker hub. I will test after my retro this morning.

I was hoping that this team would tackle that, albeit in a different story. Lost learning opportunity.

2020-12-15 15:29 UTC, jamessmckay commented on Web-Ods-AdminApp/appsettings.template.json
> +      "ProductionApiUrl": "https://localhost:5001",
Question, does the admin app have reverse proxy support?

2020-12-15 15:31 UTC, jamessmckay commented
@stephenfuqua by all means still proceed with your ticket regarding the build. I am more curious if the build will go green when we merge.

2020-12-15 15:35 UTC, stephenfuqua commented on Web-Ods-AdminApp/appsettings.template.json
> +      "ProductionApiUrl": "https://localhost:5001",
If we're centralizing on 443, I interpret that to mean we'll want https://localhost/api and https://localhost/admin-app. Is that correct? Then we can make a change in the nginx file right now to help with merging updates. I am certain this will require some additional work in Admin App, but we can explore that with ODST-160. I'm going to make the suggestion over in the correct place.

2020-12-15 15:36 UTC, stephenfuqua commented on Web-Ods-AdminApp/README.md
> +As for any pre-built image usage, it is the image user's responsibility to ensure that any use of this image complies with any relevant licenses for all software contained within.
Feel free to create a ticket. These are my personal review comments and requests for this particular file. We should consider - separately - if we want to publish a formal markdown style convention document.

2020-12-15 15:38 UTC, blmeyers commented on .env.example
> +ADMINAPP_BULKUPLOAD_FOLDER=<path to store admin app bulk upload hash cache files>
Putting it on a persistent volume is fine, and can be achieved without using any environment variables (see how the persistent volumes for PostgreSQL are set up).  Putting a path in here implies that you want to store the files in a known host folder so that the end user can easily access them (for example, the log path is set up through an environment variable) rather than just storing them internal to the docker infrastructure.  Does this path need to be user accessible or can it just be set up as an internal persistent volume?

2020-12-15 15:38 UTC, stephenfuqua commented on Web-Ods-AdminApp/Dockerfile
> +ENV VERSION="2.1.0-pre0003"
It is really just the pre-release number churn that I am thinking about avoiding. But maybe that churn is acceptable? Perhaps I should just wait and see how much churn we really have.

2020-12-15 15:39 UTC, stephenfuqua commented on .env.example
> +ADMINAPP_BULKUPLOAD_FOLDER=<path to store admin app bulk upload hash cache files>
Oh, I see your point. Yes, we can/should change that. @CSR2017 ping me in Slack if you have any doubt about how to change that.

2020-12-15 15:41 UTC, stephenfuqua commented on Web-Gateway/nginx.conf
> +   }
@CSR2017 suggestion to remove this `server` section and instead add the following block after line 40 above:

```
        location /admin-app/ {
            proxy_pass  http://adminapp/;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port 5001;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
```

We had discussed this possibility yesterday and now it looks like we have a compelling reason to go this direction.

2020-12-15 19:08 UTC, jamessmckay commented on Web-Gateway/nginx.conf
> +   }
Issue I have with this solution, is that it will not work in this deployment. We still need to use ports until the reverse proxy is merged. I am suggesting you create a ticket to address this change after reverse proxy is supported.

2020-12-15 19:09 UTC, jamessmckay commented on Web-Ods-AdminApp/appsettings.template.json
> +      "ProductionApiUrl": "https://localhost:5001",
We are releasing reverse proxy after the admin app support. This change needs to go after that.

2020-12-15 19:17 UTC, vimayya commented on Web-Ods-AdminApp/appsettings.template.json
> +      "ProductionApiUrl": "https://localhost:5001",
@stephenfuqua Docker part of ODS-4594 isn't merged, as it involved API changes and will not work with ODS / API 5.1.0  ODS-160 needs to wait until after the MVP release. If there is bandwidth, team could verify reverse proxy and virtual path support in Admin App.

2020-12-15 19:43 UTC, stephenfuqua commented on Web-Ods-AdminApp/appsettings.template.json
> +      "ProductionApiUrl": "https://localhost:5001",
OK, we can just leave it as is for now.

2020-12-15 19:45 UTC, stephenfuqua commented on Web-Gateway/nginx.conf
> +   }
Vinaya created a ticket already. The change above has no bearing on the API - only on Admin App. Still, we can easily hold off on it. So @CSR2017 please leave nginx conf alone at this time.

2020-12-16 14:27 UTC, jamessmckay requested changes
@CSR2017 
There are still some changes that needs to be addressed (including updating the other compose file); I am also getting an error with the startup of Admin App.
```
psql: error: could not connect to server: Connection refused
	Is the server running on host "db-ods" (172.18.0.3) and accepting
	TCP/IP connections on port 5432?
Postgres is unavailable - sleeping
psql: error: could not connect to server: Connection refused
	Is the server running on host "db-ods" (172.18.0.3) and accepting
	TCP/IP connections on port 5432?
Postgres is unavailable - sleeping
psql: error: could not connect to server: Connection refused
	Is the server running on host "db-ods" (172.18.0.3) and accepting
	TCP/IP connections on port 5432?
Postgres is unavailable - sleeping
psql: error: could not connect to server: Connection refused
	Is the server running on host "db-ods" (172.18.0.3) and accepting
	TCP/IP connections on port 5432?
Postgres is unavailable - sleeping
Postgres is up - executing command
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {9058ba47-f7c8-4e5e-aef3-b1c3ba6137b4} may be persisted to storage in unencrypted form.
info: Hangfire.BackgroundJobServer[0]
      Starting Hangfire Server using job storage: 'PostgreSQL Server: Host: db-admin, DB: EdFi_Admin, Schema: adminapp_hangfire'
info: Hangfire.BackgroundJobServer[0]
      Using the following options for SQL Server job storage:
info: Hangfire.BackgroundJobServer[0]
          Queue poll interval: 00:00:15.
info: Hangfire.BackgroundJobServer[0]
          Invisibility timeout: 00:30:00.
info: Hangfire.BackgroundJobServer[0]
      Using the following options for Hangfire Server:
          Worker count: 20
          Listening queues: 'default'
          Shutdown timeout: 00:00:15
          Schedule polling interval: 00:00:15
info: Hangfire.Server.BackgroundServerProcess[0]
      Server adminapp:17:65477fb7 successfully announced in 272.4385 ms
info: Hangfire.Server.BackgroundServerProcess[0]
      Server adminapp:17:65477fb7 is starting the registered dispatchers: ServerWatchdog, ServerJobCancellationWatcher, ExpirationManager, Worker, DelayedJobScheduler, RecurringJobScheduler...
info: Hangfire.Server.BackgroundServerProcess[0]
      Server adminapp:17:65477fb7 all the dispatchers started
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (9ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT u.id, u.accessfailedcount, u.concurrencystamp, u.email, u.emailconfirmed, u.lockoutenabled, u.lockoutend, u.normalizedemail, u.normalizedusername, u.passwordhash, u.phonenumber, u.phonenumberconfirmed, u.requirepasswordchange, u.securitystamp, u.twofactorenabled, u.username
      FROM adminapp.users AS u
      WHERE FALSE = TRUE
      LIMIT 2
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'EdFi.Ods.AdminApp.Management.Database.AdminAppIdentityDbContext'.
      Npgsql.PostgresException (0x80004005): 42P01: relation "adminapp.users" does not exist
         at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
         at Npgsql.NpgsqlDataReader.NextResult()
         at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
         at System.Data.Common.DbCommand.ExecuteReader()
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
         at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
        Exception data:
          Severity: ERROR
          SqlState: 42P01
          MessageText: relation "adminapp.users" does not exist
          Position: 288
          File: parse_relation.c
          Line: 1156
          Routine: parserOpenTable
Npgsql.PostgresException (0x80004005): 42P01: relation "adminapp.users" does not exist
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
  Exception data:
    Severity: ERROR
    SqlState: 42P01
    MessageText: relation "adminapp.users" does not exist
    Position: 288
    File: parse_relation.c
    Line: 1156
    Routine: parserOpenTable
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
Npgsql.PostgresException (0x80004005): 42P01: relation "adminapp.users" does not exist
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject param [...]

2020-12-16 14:27 UTC, jamessmckay commented on Web-Gateway/nginx.conf
> +   }
@CSR2017 sugi, we need to use ports here. This change needs to be done on a separate ticket.

2020-12-16 14:27 UTC, jamessmckay commented on Web-Ods-AdminApp/README.md
> +
@CSR2017 this change is still needed please

2020-12-16 14:35 UTC, jamessmckay commented
@CSR2017 Sugi, the powershell script needs to be updated to clean up the image for admin app to please

2020-12-16 14:51 UTC, stephenfuqua commented on Web-Ods-AdminApp/README.md
> +
Suganya, this readme is actually incorporated into the Docker Hub page describing the published image. That's why we have a link back to the repository.

```suggestion
[1.1.0](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker/blob/main/Web-Ods-Admin/Dockerfile)

## Image Variants

The only supported image at this time is an Alpine-based implementation.

`edfialliance/ods-admin-app:<version>`
```

2020-12-16 14:56 UTC, stephenfuqua commented
@jamessmckay you are getting errors when you start up because you haven't manually run the Admin App db migrations - the topic I brought up in Slack this morning. In the scope of the current ticket you have to manually deploy. I am seriously considering if we should create a longish-running feature branch for this merge instead of going directly into `main`, because as is we're introducing code that doesn't work out of the box. I don't like either but I think I like a temporary branch better than broken solution.

> "There are still some changes that needs to be addressed (including updating the other compose file); I am also getting an error with the startup of Admin App."

We have a separate ticket for dealing with the other compose file. The current ticket is only for the local developer build.

2020-12-16 15:35 UTC, stephenfuqua commented on Web-Ods-AdminApp/appsettings.template.json
> +      "OptionalEntropy": "OptionalEntropy",
We need to change this so that we create a random value. I need to think about it further and will create a separate ticket. The entropy should never be "hard coded" like this.

2020-12-16 18:11 UTC, stephenfuqua commented on Web-Ods-AdminApp/README.md
> +Provides docker deployment for Ed-Fi ODS ADMIN APP [v2.1.0](https://techdocs.ed-fi.org/pages/viewpage.action?pageId=83788284).
```suggestion
Provides docker deployment for [Ed-Fi ODS Admin App v2.1.0](https://techdocs.ed-fi.org/display/ADMIN).
```

2020-12-16 19:16 UTC, stephenfuqua approved these changes

2020-12-16 19:18 UTC, jamessmckay approved these changes

2020-12-16 19:18 UTC, merged