[AA-821] Install database support in docker
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #36
Opened 2020-12-28 21:08 UTC by CSR2017

@jamessmckay @stephenfuqua 
Please help review and merge the changes.
1. Downloading admin app database scripts from azure on Db-Admin/Dockerfile
2. On Db-Admin/init-database.sh executing admin app db scripts conditionally 
3. Added api mode on db_admin and encryption key on admin app compose section
4. Admin app version update and corresponding appsettings changes.
Thanks

2021-01-04 16:44 UTC, stephenfuqua commented on DB-Admin/Dockerfile
> +    wget -O /tmp/EdFi_AdminApp_Scripts.zip https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_apis/packaging/feeds/EdFi/nuget/packages/EdFi.Suite3.ODS.AdminApp.Database/versions/${ADMINAPP
The feed url should probably be a variable. Can you refactor this to introduce a constant value on line 16?

2021-01-04 16:44 UTC, stephenfuqua commented on DB-Admin/init-database.sh
> +if [ "${API_MODE,,}" = "sharedinstance" ]; then
What is the significance of the two commas in the line above? I'm very rusty with bash shell scripting.

2021-01-04 16:44 UTC, stephenfuqua commented on compose-shared-instance-env-build.yml
> +      ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
Why is this here in this pull request? Does not seem to be related to AA-821. Was this just overlooked in AA-1131?

2021-01-04 20:20 UTC, CSR2017 commented on compose-shared-instance-env-build.yml
> +      ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
@stephenfuqua 
Yes, since the needed changes from AA-1131 for successful testing. Added as part of these changes.

2021-01-04 20:23 UTC, CSR2017 commented on DB-Admin/init-database.sh
> +if [ "${API_MODE,,}" = "sharedinstance" ]; then
@stephenfuqua 
To convert to lower case. Had other options, but chose to use the inbuilt option.

2021-01-04 20:45 UTC, stephenfuqua commented on DB-Admin/init-database.sh
> +if [ "${API_MODE,,}" = "sharedinstance" ]; then
What an obscure syntax for changing the case!

2021-01-04 22:57 UTC, jamessmckay commented on DB-Admin/Dockerfile
> +    wget -O /tmp/EdFi_AdminApp_Scripts.zip https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_apis/packaging/feeds/EdFi/nuget/packages/EdFi.Suite3.ODS.AdminApp.Database/versions/${ADMINAPP
I would suggest we spin off another ticket for the feed as a variable because we should probably do that for all the docker files

2021-01-04 23:00 UTC, jamessmckay requested changes

2021-01-05 14:58 UTC, stephenfuqua commented on DB-Admin/Dockerfile
> +    wget -O /tmp/EdFi_AdminApp_Scripts.zip https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_apis/packaging/feeds/EdFi/nuget/packages/EdFi.Suite3.ODS.AdminApp.Database/versions/${ADMINAPP
I will create a ticket for the ODS/API-related Docker files.

2021-01-05 15:06 UTC, stephenfuqua commented on DB-Admin/Dockerfile
> +    dos2unix /tmp/AdminAppScripts/PgSql/*
These are migration scripts for use with DbUp, not a backup-and-restore.

2021-01-05 15:09 UTC, stephenfuqua commented on DB-Admin/init-database.sh
> +if [ "${API_MODE,,}" = "sharedinstance" ]; then
I could go either way. "do just one thing" suggests to have a separate file. However, it is very easy to reason about which init script is running and very easy to read this script.

Eventually we'll want to install Admin App scripts for District and Year specific modes as well. Right now only goal is shared instance. Maybe it would make sense to have `init-sandbox.sh` and `init-production.sh`?

2021-01-05 20:27 UTC, jamessmckay commented on DB-Admin/Dockerfile
> +    dos2unix /tmp/AdminAppScripts/PgSql/*
How will this work then? Currently we restore the database using psql.

2021-01-05 20:31 UTC, jamessmckay commented on DB-Admin/init-database.sh
> +if [ "${API_MODE,,}" = "sharedinstance" ]; then
well production could be shared instance, or sandbox,  or instance specific, or year specific. Even though we advertise shared instance at the moment. (The ODS works fine in the other instances on docker). I think adding a check in the main init-database.sh to call the correct shell script  for further processing may make sense. However this could be a separate ticket for the future.

2021-01-05 21:53 UTC, stephenfuqua commented on DB-Admin/Dockerfile
> +    dos2unix /tmp/AdminAppScripts/PgSql/*
@CSR2017 please address this question

2021-01-05 22:01 UTC, jamessmckay commented on DB-Admin/Dockerfile
> +    dos2unix /tmp/AdminAppScripts/PgSql/*
The biggest concern is keeping the scripts in order. @CSR2017 will create a ticket to address that concern.

2021-01-05 22:16 UTC, jamessmckay approved these changes

2021-01-06 16:01 UTC, CSR2017 commented on DB-Admin/init-database.sh
> +if [ "${API_MODE,,}" = "sharedinstance" ]; then
Ticket created for moving the AdminApp specific code implementation to a separate file https://tracker.ed-fi.org/browse/AA-1210.

2021-01-06 16:37 UTC, CSR2017 commented on DB-Admin/Dockerfile
> +    dos2unix /tmp/AdminAppScripts/PgSql/*
Created ticket for solving script execution order https://tracker.ed-fi.org/browse/AA-1211

2021-01-07 19:53 UTC, stephenfuqua approved these changes

2021-01-07 19:53 UTC, merged