[ODS-4790] Admin App
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #47
Opened 2021-01-25 17:28 UTC by stephenfuqua

2021-01-25 18:40 UTC, jamessmckay requested changes

2021-01-25 18:40 UTC, jamessmckay commented on .env.example
> +TAG=<version tag of the ODS/API images>
This tag is related to the tag version of the docker images.

2021-01-25 18:40 UTC, jamessmckay commented on DB-Admin/README.md
> +Provides docker deployment for **_EdFi_Admin_** and **_EdFi_Security_** database
why is there all this whitespace changes?

2021-01-25 18:40 UTC, jamessmckay commented on DB-Admin/init-database.sh
> +if [ "${API_MODE,,}" = "sharedinstance" ]; then
Is there a ticket to address this as a separate file in the future?

2021-01-25 18:40 UTC, jamessmckay commented on README.md
> +TAG=<version tag of the ODS/API images>
This tag is related to the tag of the docker image.

2021-01-25 18:40 UTC, jamessmckay commented on Web-Gateway/nginx.conf
> +        location /productionLearningStandardsHub {
per our conversation, may need to do a regression test to validate there will be no blocking issues since this is a separate process.

2021-01-25 18:40 UTC, jamessmckay commented on Web-Ods-AdminApp/appsettings.template.json
> +      "EncryptionKey": "$ENCRYPTION_KEY"
remove extra whitespace please

2021-01-25 18:40 UTC, jamessmckay commented on Web-Ods-AdminApp/run.sh
> +sleep 10
should there be another check to validate that the other database is complete instead?

2021-01-25 18:40 UTC, jamessmckay commented on compose-shared-instance-env.yml
>      image: edfialliance/ods-api-web-api:${TAG}
I do not see the value in having different versions of the tag versions. The usage is that a user will use v1 as the tag version or latest, which will always pull the latest.

2021-01-25 18:40 UTC, jamessmckay commented on compose-shared-instance-env.yml
> +      API_MODE: "SharedInstance"
this should be a reference from the env file.

2021-01-25 18:40 UTC, jamessmckay commented on compose-shared-instance-env.yml
> +      - adminapp-bulk-hashcache:/app/BulkUploadHashCache
Should we map to a known folder location instead of having to dig it out of the docker locations

2021-01-25 19:32 UTC, stephenfuqua commented on .env.example
> +TAG=<version tag of the ODS/API images>
I'm not clear what you are getting at...

2021-01-25 19:33 UTC, stephenfuqua commented on DB-Admin/README.md
> +Provides docker deployment for **_EdFi_Admin_** and **_EdFi_Security_** database
b/c I wrapped the text so that it is easier to read

2021-01-25 19:35 UTC, stephenfuqua commented on DB-Admin/init-database.sh
> +if [ "${API_MODE,,}" = "sharedinstance" ]; then
AA-1210, although I disagree with the premise and think it should be closed

2021-01-25 19:38 UTC, stephenfuqua commented on .env.example
> +ODS_ADMIN_APP_TAG=<version tag of the ods-admin-app image>
@plioi now that I have reviewed the docker hub build process, I can see that there is no value in separating the `TAG` from `ODS_ADMIN_APP_TAG`. Since the dockerfiles are in the same repository, every release will update all images; Docker does not support triggering a build based on watching particular directories. If we want to be able to version Admin App separately then we'll need to move its Dockerfile to the Admin App repository.

2021-01-25 19:39 UTC, stephenfuqua commented on Web-Gateway/nginx.conf
> +        location /productionLearningStandardsHub {
That is naturally part of the full regression test process that the Tools team will work on. Thank you for bringing it to our attention.

2021-01-25 19:40 UTC, stephenfuqua commented on Web-Ods-AdminApp/appsettings.template.json
> +      "EncryptionKey": "$ENCRYPTION_KEY"
I don't see any extra whitespace.

2021-01-25 19:41 UTC, stephenfuqua commented on Web-Ods-AdminApp/appsettings.template.json
> +      "EncryptionKey": "$ENCRYPTION_KEY"
Oh, its hidden in github. This is why everyone needs the the editorconfig plugin in VS Code - it always strips off extra whitespace.

2021-01-25 19:42 UTC, stephenfuqua commented on Web-Ods-AdminApp/run.sh
> +sleep 10
Oh, good point. I hadn't looked closely at which database is in line 9. If only testing one, should be admin database. Better to test both.

2021-01-25 19:43 UTC, stephenfuqua commented on compose-shared-instance-env.yml
>      image: edfialliance/ods-api-web-api:${TAG}
I think the team was thinking about release admin-app dockerfile updates out of band with the API. That's not really feasible right now, so I agree there is no point in having separate variables.

2021-01-25 19:44 UTC, plioi commented on .env.example
> +TAG=<version tag of the ODS/API images>
Just filling in the conversation: over in the documentation page in progress, Jim rightly called out that we didn't need a distinct environment variable for AA's own tag, so #48 is reverting that. #48 is also reverting our mistake update to the <documentation text in brackets here> to rightly describe it as THE image tag version.

2021-01-25 19:44 UTC, stephenfuqua commented on compose-shared-instance-env.yml
> +      API_MODE: "SharedInstance"
This compose file is explicitly for shared instance and should not be used for other modes.

2021-01-25 19:45 UTC, stephenfuqua commented on compose-shared-instance-env.yml
> +      - adminapp-bulk-hashcache:/app/BulkUploadHashCache
This is not a feature that a user would ever look at, so we've done this deliberately. This is a weird process that writes out a little file with a hash value in it, as a sort of log. I have ticket to change that for writing to the database instead. I was flabbergasted when I saw this process.

2021-01-25 19:45 UTC, plioi commented on README.md
> +TAG=<version tag of the ODS/API images>
Getting fixed in #48

2021-01-25 19:46 UTC, plioi commented on compose-shared-instance-env.yml
>      image: edfialliance/ods-api-web-api:${TAG}
See #48

2021-01-25 19:46 UTC, plioi commented on compose-shared-instance-env.yml
> +      API_MODE: "SharedInstance"
Even here in the shared-instance yml file?

2021-01-25 19:47 UTC, plioi commented on .env.example
> +ODS_ADMIN_APP_TAG=<version tag of the ods-admin-app image>
Agreed, reverting in #48

2021-01-25 19:57 UTC, plioi commented on compose-shared-instance-env.yml
> +      - adminapp-bulk-hashcache:/app/BulkUploadHashCache
FWIW this corresponds with the EdFi.LoadTools.dll's Configuration.WorkingDirectory property, so it's not an Admin App concept alone.

2021-01-25 22:12 UTC, plioi commented on .env.example
> +TAG=<version tag of the ODS/API images>
Fixed.

2021-01-25 22:13 UTC, plioi commented on README.md
> +TAG=<version tag of the ODS/API images>
Fixed.

2021-01-25 22:14 UTC, plioi commented on compose-shared-instance-env.yml
>      image: edfialliance/ods-api-web-api:${TAG}
Fixed. We're using TAG here now.

2021-01-25 22:15 UTC, plioi commented on .env.example
> +ODS_ADMIN_APP_TAG=<version tag of the ods-admin-app image>
Fixed.

2021-01-25 22:21 UTC, plioi commented on Web-Ods-AdminApp/appsettings.template.json
> +      "EncryptionKey": "$ENCRYPTION_KEY"
Fixed in d2b2ef433f3ad37aac829860fbb60b292af6030d

2021-01-25 23:22 UTC, plioi commented on Web-Ods-AdminApp/run.sh
> +sleep 10
Fixed in f618cb83aa1abbc8ad0d2bfe5f2636d90c16bf45

We now wait for both databases using the same technique. I slightly modified the content of the `echo` commands so that it's clear which one is being waited on.

Attaching screenshot of the relevant in-container log entries:

![image](https://user-images.githubusercontent.com/652745/105778297-bfc00200-5f31-11eb-8540-bac487113dc7.png)

2021-01-26 13:48 UTC, jamessmckay commented on DB-Admin/README.md
> +Provides docker deployment for **_EdFi_Admin_** and **_EdFi_Security_** database
please revert the whitespace changes

2021-01-26 13:50 UTC, jamessmckay commented on Web-Ods-AdminApp/run.sh
> +sleep 10
@plioi please create a ticket for the fix on f618cb8 and open a pull request for it please

2021-01-26 13:51 UTC, jamessmckay commented on compose-shared-instance-env.yml
> +      API_MODE: "SharedInstance"
my thoughts here is that these compose files are samples. I would rather see them being built correctly so that a user can build there own.

2021-01-26 13:53 UTC, jamessmckay commented on compose-shared-instance-env.yml
> +      - adminapp-bulk-hashcache:/app/BulkUploadHashCache
I am more concerned about that the ability of the files being written. Ideally if you deploy in linux you would map to a folder that you can lock down. Also if you are running the docker files under linux (for example Innive), you cannot write to the docker folder.

2021-01-26 14:06 UTC, jamessmckay requested changes

2021-01-26 14:06 UTC, jamessmckay commented on compose-shared-instance-for-local-debug.yml
> +# suitable anywhere except for local development and testing.
Why is this compose file needed?

2021-01-26 14:06 UTC, stephenfuqua commented on compose-shared-instance-env.yml
> +      - adminapp-bulk-hashcache:/app/BulkUploadHashCache
After looking at this several times, I think I understand the problem: there is a typo, and the volume is not actually being used here.

```suggestion
      - vol-adminapp-bulk-hashcache:/app/BulkUploadHashCache
```

2021-01-26 14:09 UTC, stephenfuqua commented on compose-shared-instance-for-local-debug.yml
> +# suitable anywhere except for local development and testing.
Probably isn't needed anymore. Was very useful in early debugging of Admin App's connection to the ODS/API. I think it is safe to remove it without impacting the team.

2021-01-26 14:11 UTC, stephenfuqua commented on compose-shared-instance-env.yml
> +      API_MODE: "SharedInstance"
A user building their own file cannot change this value to anything else and have it run successfully. I do not see any upside - only downside - to changing this.

2021-01-26 14:18 UTC, stephenfuqua commented on compose-shared-instance-env.yml
> +      - adminapp-bulk-hashcache:/app/BulkUploadHashCache
No, it was not a typo; "vol" is part of the docker volume name but the docker-compose label for the volume is indeed "adminapp-bulk-hashcache". @jamessmckay I have no idea what your objection is here or how you suggest that we remedy this, given that we're using the exact same technique applied for PostgreSQL databases.

2021-01-26 14:25 UTC, jamessmckay commented on compose-shared-instance-env.yml
> +      - adminapp-bulk-hashcache:/app/BulkUploadHashCache
good point, we should call it out that some implementations may need to map to a locked down folder in the docs...

2021-01-26 14:33 UTC, plioi commented on Web-Ods-AdminApp/run.sh
> +sleep 10
Created as #51

2021-01-26 14:35 UTC, plioi commented on compose-shared-instance-env.yml
> +      API_MODE: "SharedInstance"
Yeah, I agree with Stephen. I can't imagine this being called correct if we make this change. That would be like having the compose-sandbox-env.yml line 55 changed from "Sandbox".

2021-01-26 14:58 UTC, stephenfuqua commented on DB-Admin/README.md
> +Provides docker deployment for **_EdFi_Admin_** and **_EdFi_Security_** database
The latest commits first revert the change entirely, then reapply the formatting in one commit and update the documentation in the next commit.

2021-01-26 15:04 UTC, stephenfuqua commented on compose-shared-instance-for-local-debug.yml
> +# suitable anywhere except for local development and testing.
Removed it.

2021-01-26 15:42 UTC, jamessmckay commented on DB-Admin/README.md
> +API_MODE=<Sandbox | SharedInstance>
my question here, with admin app shipping this time with only shared instance should we not add the sandbox?

2021-01-26 15:42 UTC, jamessmckay commented on .editorconfig
> +trim_trailing_whitespace = false
should this be true?

2021-01-26 15:45 UTC, stephenfuqua commented on DB-Admin/README.md
> +API_MODE=<Sandbox | SharedInstance>
In reality, anything other than the word "SharedInstance" will give you sandbox mode. I thought it would be more clear to have the positive implication "use the word `sandbox`" than the negative "use any word other than `sharedinstance`".

2021-01-26 15:48 UTC, stephenfuqua commented on .editorconfig
> +trim_trailing_whitespace = false
Two spaces at the end of a line cause a line break rather than a paragraph break. However, allowing whitespace on the line is rather unfortunate and there is a perfectly good alternative: a slash at the end of the line. Therefore I'll remove this.

2021-01-26 16:55 UTC, jamessmckay approved these changes

2021-01-26 17:24 UTC, merged