[ODS-4861] Swagger endpoint in Docker does not work with the virtual path of docs
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #54
Opened 2021-03-18 14:25 UTC by jamessmckay

2021-03-18 15:28 UTC, stephenfuqua commented on compose-sandbox-env-build.yml
> +      UseReverseProxyHeaders: "true"
@jamessmckay: I see this setting in [ODS-Implementation](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/search?q=UseReverseProxyHeaders) but I don't see it actually being used anywhere (in C#) except in Sandbox Admin. Probably a work-in-progress, so I'm not concerned about not seeing it used yet. I just don't know exactly how it _should_ be used... so I'm curious, do you think this work has implications for Admin App? And if so, do you know if anyone has told the ODS Tools team?

2021-03-20 01:05 UTC, blmeyers requested changes

2021-03-20 17:56 UTC, jamessmckay commented on Web-Gateway-Sandbox/nginx.conf
>          # ideally this endpoint should be docs [ODS-4862]
done

2021-03-20 17:57 UTC, jamessmckay commented on compose-sandbox-env-build.yml
> +      ApiSettings__PathBase: "$ODS_VIRTUAL_NAME"
done

2021-03-23 13:44 UTC, blmeyers commented on compose-sandbox-env-build.yml
> +      RoutePrefix: "${DOCS_VIRTUAL_NAME}"
As mentioned, RoutePrefix and the Virtual Name are not the same thing.  We probably should only be setting PathBase and not setting RoutePrefix at all, and let the default of swagger remain.

2021-03-25 17:34 UTC, blmeyers requested changes

2021-03-25 17:34 UTC, blmeyers commented on compose-sandbox-env.yml
> -      PathBase: "${DOCS_VIRTUAL_NAME}"
This combined with the nginx config change are changing this in two ways.  First we're changing the way we use the reverse proxy to strip the virtual path, which is different from what we're doing for api and admin.  Second, we're not supporting a stripped virtual path on the Swagger UI, and in fact the changes over there are only supporting the scenario where you include the virtual path, we're just not using it anymore.  This probably works only because we don't generate absolute urls on the Swagger UI web site, so not having the information about the reverse proxy virtual path works out.  Should Swagger UI match what the others are doing for now until we take a more holistic approach on reverse proxy support across all three web sites? CC: @vimayya

2021-03-25 17:34 UTC, blmeyers commented on compose-sandbox-env-build.yml
>        WebApiVersionUrl: "https://localhost/${ODS_VIRTUAL_NAME}"
I don't think this was caused by these changes, but without the trailing slash on this url its causing nginx to trigger a redirect to the url with a trailing slash.  Adding the trailing slash here avoids that extra redirect.

2021-03-25 17:34 UTC, blmeyers commented on compose-sandbox-env.yml
>        WebApiVersionUrl: "https://localhost/${ODS_VIRTUAL_NAME}"
Same here about the trailing slash.

2021-03-25 17:34 UTC, blmeyers commented on compose-sandbox-env-build.yml
> +      RoutePrefix: "${DOCS_VIRTUAL_NAME}"
This environment variable is now being completely ignored, since we're looking at SwaggerUIOptions:RoutePrefix for the route prefix.  Should this just be removed?

2021-03-25 17:34 UTC, blmeyers commented on compose-sandbox-env-build.yml
> +      ApiSettings__PathBase: "$ODS_VIRTUAL_NAME"
Should this variable be surrounded with braces like the others?

2021-03-25 17:34 UTC, blmeyers commented on Web-Gateway-Sandbox/nginx.conf
> +            proxy_pass  http://swagger/;
As mentioned in a later comment, this changes swagger ui to strip the virtual path when calling through.

2021-03-25 18:33 UTC, jamessmckay commented on Web-Gateway-Sandbox/nginx.conf
> +            proxy_pass  http://swagger/;
fixed

2021-03-25 18:37 UTC, jamessmckay commented on compose-sandbox-env-build.yml
> +      ApiSettings__PathBase: "$ODS_VIRTUAL_NAME"
done

2021-03-25 18:37 UTC, jamessmckay commented on compose-sandbox-env.yml
>        WebApiVersionUrl: "https://localhost/${ODS_VIRTUAL_NAME}"
done

2021-03-25 18:38 UTC, jamessmckay commented on compose-sandbox-env-build.yml
>        WebApiVersionUrl: "https://localhost/${ODS_VIRTUAL_NAME}"
done

2021-03-26 00:25 UTC, blmeyers approved these changes

2021-03-26 13:45 UTC, vimayya commented on Web-Gateway-Sandbox/nginx.conf
> +        location /docs/ {
@jamessmckay since ODS-4861 didn't make into the api release, shouldn't we keep this at the root for now?

2021-03-26 13:46 UTC, vimayya commented on Web-SwaggerUI/Dockerfile
> +ENV VERSION="5.2.14374"
@jamessmckay Let's keep this at release version 5.2.14406

2021-03-26 14:44 UTC, jamessmckay commented on Web-Gateway-Sandbox/nginx.conf
> +        location /docs/ {
Yes it will need to be changed back to the root for the 2.0 release. I will spin a ticket off to address that along with the packages to be bumped to 5.2.0

2021-03-26 14:44 UTC, jamessmckay commented on Web-SwaggerUI/Dockerfile
> +ENV VERSION="5.2.14374"
Agreed. That should go on a separate ticket.

2021-03-29 15:13 UTC, blmeyers commented
As per sidebar discussion, closing this PR until after the next docker release.  Branch will remain and will come in at a later date.

2021-03-29 15:13 UTC, closed without merging