[ODS-4742] PostgreSQL Connection Pooling
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #56
Opened 2021-03-30 13:56 UTC by jamessmckay

2021-03-31 15:34 UTC, jamessmckay commented on Web-Ods-AdminApp/appsettings.template.json
> +    "Admin": "host=${ADMIN_DB};port=${POSTGRES_PORT};username=${POSTGRES_USER};password=${POSTGRES_PASSWORD};database=EdFi_Admin;pooling=false;client encoding=utf-8;Application Name=EdFi.Ods.AdminApp
note it was recommended to disable pooling at the client level

2021-03-31 21:55 UTC, blmeyers requested changes

2021-03-31 21:55 UTC, blmeyers commented on compose-sandbox-env-build.yml
> +version: '3.9'
Sneaking a docker compose version bump in this ticket seems risky.

2021-03-31 21:55 UTC, blmeyers commented on Web-Sandbox-Admin/run.sh
> +until PGPASSWORD=$POSTGRES_PASSWORD psql -h $ODS_DB -p $POSTGRES_PORT -U $POSTGRES_USER -c '\q';
If I'm understanding this correctly, we're passing the actual postgresql port into this script, so it can ping it to see if its up.  But once Admin is running, its going to be connecting through the bouncer, so shouldn't this check be verifying connectivity through the bouncer?

2021-03-31 21:55 UTC, blmeyers commented on .env.example
> +POSTGRES_PORT=<port to run postgres on>
We seem to be using this to set the underlying PostgreSql port, but is that actually important in this setup?  Given the bouncer setup, this port would never be directly exposed.  Is this intended to provide the ability to set the exposed bouncer port for direct access from outside the container infrastructure? Should we have environment variables for both?

2021-03-31 21:55 UTC, blmeyers commented on compose-shared-instance-env.yml
> +      POSTGRES_PORT: 6432
We added a POSTGRES_PORT to the env file, but we're not actually using it here?  Its only used on the bouncer configuration, so if you don't set it in the env file it blows up bouncer startup.  See comments on that variable, but wherever we land on these variables we need to make sure we're using them everywhere in the compose file (and passing down to the docker file where needed).

2021-03-31 21:55 UTC, blmeyers commented on Web-Ods-AdminApp/run.sh
> +if [[ -z "$POSTGRES_PORT" ]]; then
This is checking for POSTGRES_PORT and defaulting it, but several other places like the appsettings.json we're not handling any defaulting so its going to blow up if not set.  Shouldn't we be handling defaulting environment variables in the docker file itself?  We should also probably get another ticket to default more of these environment variables where we can (that have reasonable defaults), we keep making more and more stuff that someone has to configure in an .env when they may not even care.

2021-04-01 13:21 UTC, jamessmckay commented on compose-sandbox-env-build.yml
> +version: '3.9'
reverted

2021-04-01 13:22 UTC, jamessmckay commented on Web-Sandbox-Admin/run.sh
> +until PGPASSWORD=$POSTGRES_PASSWORD psql -h $ODS_DB -p $POSTGRES_PORT -U $POSTGRES_USER -c '\q';
no we pass in the bouncer port from the compose file, however if bouncer is not installed then it would be the postgres server port.

2021-04-01 13:24 UTC, jamessmckay commented on .env.example
> +POSTGRES_PORT=<port to run postgres on>
Looking at your comment below, I am going to introduce a variable for the bouncer port.

2021-04-06 13:41 UTC, blmeyers commented on DB-ODS/init-database.sh
> +if [[ -z "$POSTGRES_PORT" ]]; then
If this port variable has to be 5432, all of this handling should just go away. Either way, defaulting like this should be in the docker file not in the bash scripts.

2021-04-06 13:41 UTC, blmeyers commented on DB-Sandbox/init-database.sh
> +if [[ -z "$POSTGRES_PORT" ]]; then
If this port variable has to be 5432, all of this handling should just go away. Either way, defaulting like this should be in the docker file not in the bash scripts.

2021-04-06 13:41 UTC, blmeyers commented on Web-Ods-AdminApp/run.sh
> +if [[ -z "$PGBOUNCER_LISTEN_PORT" ]];
Shouldn't this just take the port to connect to PostgreSQL on, and not be aware of the listener concept?  All this docker template needs to know is where to go for PostgreSQL.

2021-04-06 13:41 UTC, blmeyers commented on Web-Ods-AdminApp/run.sh
> +until PGPASSWORD=$POSTGRES_PASSWORD psql -h $ODS_DB -p $POSTGRES_PORT -U $POSTGRES_USER -c '\q';
This is a good example of what we should probably be doing for the port as well, with $ODS_DB.  Pass the host name for the instance in, don't worry if its a bouncer or a regular instance.

2021-04-06 13:41 UTC, blmeyers commented on Web-Ods-Api/run.sh
> +if [[ -z "$PGBOUNCER_LISTEN_PORT" ]];
Shouldn't this just take the port to connect to PostgreSQL on, and not be aware of the listener concept? All this docker template needs to know is where to go for PostgreSQL.

2021-04-06 13:41 UTC, blmeyers commented on Web-Sandbox-Admin/run.sh
> +if [[ -z "$PGBOUNCER_LISTEN_PORT" ]];
Shouldn't this just take the port to connect to PostgreSQL on, and not be aware of the listener concept? All this docker template needs to know is where to go for PostgreSQL.

2021-04-06 13:41 UTC, blmeyers commented on compose-sandbox-env-build.yml
> +      POSTGRES_PORT: "${POSTGRES_PORT}"
From refinement discussion, if this port doesn't actually work to change the PG Port, then we should clean up this variable.

2021-04-06 13:41 UTC, blmeyers commented on compose-sandbox-env-build.yml
> +      POSTGRES_PORT: "${POSTGRES_PORT}"
Same for this port.

2021-04-06 15:21 UTC, jamessmckay commented on compose-sandbox-env-build.yml
> +      UseReverseProxyHeaders: "true"
done

2021-04-06 15:25 UTC, jamessmckay commented on compose-sandbox-env-build.yml
> +      UseReverseProxyHeaders: "true"
done

2021-04-06 15:25 UTC, jamessmckay commented on .env.example
> +PGBOUNCER_LISTEN_PORT=<port for pg bouncer to listen to>
done

2021-04-06 15:25 UTC, jamessmckay commented on DB-ODS/init-database.sh
> +if [[ -z "$POSTGRES_PORT" ]]; then
done

2021-04-06 15:25 UTC, jamessmckay commented on DB-Sandbox/init-database.sh
> +if [[ -z "$POSTGRES_PORT" ]]; then
done

2021-04-06 15:26 UTC, jamessmckay commented on Web-Ods-AdminApp/run.sh
> +if [[ -z "$PGBOUNCER_LISTEN_PORT" ]];
done

2021-04-06 15:26 UTC, jamessmckay commented on Web-Ods-AdminApp/run.sh
> +until PGPASSWORD=$POSTGRES_PASSWORD psql -h $ODS_DB -p $POSTGRES_PORT -U $POSTGRES_USER -c '\q';
ODS_DB renamed to ODS_POSTGRES_HOST

2021-04-06 15:26 UTC, jamessmckay commented on Web-Ods-Api/run.sh
> +if [[ -z "$PGBOUNCER_LISTEN_PORT" ]];
done

2021-04-06 15:26 UTC, jamessmckay commented on Web-Sandbox-Admin/run.sh
> +if [[ -z "$PGBOUNCER_LISTEN_PORT" ]];
done

2021-04-06 15:26 UTC, jamessmckay commented on compose-sandbox-env-build.yml
> +      POSTGRES_PORT: "${POSTGRES_PORT}"
done

2021-04-06 15:26 UTC, jamessmckay commented on compose-sandbox-env-build.yml
> +      POSTGRES_PORT: "${POSTGRES_PORT}"
done

2021-04-07 19:56 UTC, blmeyers approved these changes

2021-04-07 20:16 UTC, merged