[ODS-4905] Bump docker files to latest version of the ODS
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #57
Opened 2021-03-30 17:08 UTC by jamessmckay

2021-03-30 19:26 UTC, vimayya commented on DB-Admin/Dockerfile
> +ENV ADMIN_VERSION="5.2.10084"
release promoted versions are 
admin - 5.2.10083
security - 5.2.10103

2021-03-31 15:54 UTC, tbmeador-dlp requested changes
just need to fix the admin and security database versions, everything else looks good

2021-03-31 15:54 UTC, tbmeador-dlp commented on DB-Admin/Dockerfile
> +ENV ADMIN_VERSION="5.2.10084"
@jamessmckay these still need to be updated to the ones @vimayya mentioned. The versions you have here have unmerged changes from the ODS-4718 branch.

2021-04-01 17:30 UTC, tbmeador-dlp approved these changes

2021-04-01 17:31 UTC, merged