[ODS-4860] Add Http -> Https Redirection for Docker
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #58
Opened 2021-03-30 18:30 UTC by jamessmckay

2021-03-31 21:10 UTC, blmeyers requested changes

2021-03-31 21:10 UTC, blmeyers commented on Web-Gateway/nginx.conf
> +        server_name localhost;
Why are we locking to localhost here?  Why not follow the pattern provided in the linked article from the ticket, using "_" as the server_name to match all requests, and using "$host" in the redirect line to redirect to the url used to access it.   Following along, we should probably also set default_server for listen 80 here to match the example, since this should be the fallback server for port 80.

2021-03-31 21:10 UTC, blmeyers commented on Web-Gateway/nginx.conf
> +        server_name localhost;
Note same changes would be made in the other nginx.conf.

2021-03-31 21:10 UTC, blmeyers commented on Web-Gateway/nginx.conf
> +        listen       443 ssl default_server;
Do we actually want a default server setting here?  It makes sense for 80 since we want everything here to redirect to ssl, but not sure it would make sense here.  Probably doesn't matter since we're using everything with specific ports, but doesn't seem like something we should be forcing.

2021-04-01 12:38 UTC, jamessmckay commented on Web-Gateway/nginx.conf
> +        listen       443 ssl default_server;
I moved it due to support the change above.

2021-04-01 12:38 UTC, jamessmckay commented on Web-Gateway/nginx.conf
> +        server_name localhost;
I was torn on this, partially due to having iis installed it did not work. I will make the update.

2021-04-01 14:35 UTC, blmeyers commented on Web-Gateway/nginx.conf
> +        server_name localhost;
This looks pretty clean for local experience though.  If you try to run it with IIS holding the ports you get an error from nginx and the container won't start.  Stopping the web site or stopping the iis windows service let's you stand it up fine.  I think it makes sense to default to standard ports, but there's probably value in eventually templating nginx config and letting you run an env file with different ports, just to not have to keep messing with IIS for local development.

![image](https://user-images.githubusercontent.com/364312/113310045-65df0e00-92cd-11eb-8a20-9bab0223abca.png)

2021-04-01 14:51 UTC, blmeyers approved these changes

2021-04-01 14:51 UTC, merged