Ods 4475 PSQL-ODS
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #6
Opened 2020-10-22 16:01 UTC by ptar-innive

2020-10-22 16:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker?pullRequest=6) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker?pullRequest=6) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: ptar-innive<br/>:x: dalluinniveinc<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker?pullRequest=6) it.</sub>

2020-10-22 16:02 UTC, ptar-innive commented on PSQL-ODS/docker-entrypoint.sh
> +psql -d postgres -c "CREATE USER pguser WITH PASSWORD 'password@';"
@dalluinniveinc please use password from /app/pgpass file

2020-10-26 06:45 UTC, dalluinniveinc commented on PSQL-ODS/docker-entrypoint.sh
> +psql -d postgres -c "CREATE USER pguser WITH PASSWORD 'password@';"
updated the Dockerfile for ODS-4475

2020-10-28 13:09 UTC, jamessmckay requested changes

2020-10-28 13:09 UTC, jamessmckay commented on PSQL-ODS/Dockerfile
> +#Need to copy *.sql files to "docker-entrypoint-initdb.d" from local machine otherwise getting errorr while copying files
```suggestion
#Need to copy *.sql files to "docker-entrypoint-initdb.d" from local machine otherwise getting error while copying files

```

2020-10-28 13:12 UTC, jamessmckay approved these changes

2020-10-28 13:13 UTC, merged