[AA-1291] Use environment variable for ProductionApiUrl in appsettings.template.json
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #64
Opened 2021-04-16 21:29 UTC by CSR2017

@stephenfuqua @jamessmckay @plioi 
Please help review and merge the changes.
Thanks

2021-04-20 16:25 UTC, saa14 approved these changes

2021-04-21 13:17 UTC, stephenfuqua approved these changes
I did not test, but it certainly _looks_ good to me.

2021-04-21 13:33 UTC, jamessmckay requested changes
@CSR2017 Sugi, we have streamlined how we are doing defaults for some of these environment variables and that will be going in later today. Check out pr https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker/pull/62 for what is coming. Could you please update to use the same pattern.

2021-04-22 12:04 UTC, jamessmckay approved these changes

2021-04-22 14:06 UTC, jamessmckay requested changes
@CSR2017 sugi this looks good, however can you add a default to the admin app docker file for `ADMINAPP_VIRTUAL_NAME` and `API_INTERNAL_URL` please.

2021-04-23 17:18 UTC, jamessmckay approved these changes

2021-04-23 17:18 UTC, merged