[AA-1287] - Updated appsettings for AdminApp along with nuget package version updates
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #68
Opened 2021-04-26 21:09 UTC by saa14

**Description**

- Updated the AdminApp nuget package versions to the latest pre-release versions. 
**(A second final PR will update the files to use the 2.2.0 versions)**
- Successfully completed regression testing 
- Removed deprecated appsettings: SystemManagedSqlServer, DbSetupEnabled and EncryptionProtocol. 
- Added GoogleAnalyticsMeasurementId appsetting.

2021-04-27 20:00 UTC, jamessmckay requested changes

2021-04-27 20:00 UTC, jamessmckay commented on Web-Ods-AdminApp/run.sh
> +apk add jq
the apk command needs to move to the docker file and it also needs to be locked to a version to pass linting.

2021-04-27 20:00 UTC, jamessmckay commented on Web-Ods-AdminApp/run.sh
> +tmp=$(mktemp)
are you intending to use /tmp?

2021-04-27 20:29 UTC, plioi commented on Web-Ods-AdminApp/run.sh
> +tmp=$(mktemp)
No, just a temporary file since jq cannot read from and write to the same file in one go.

2021-04-27 20:30 UTC, plioi commented on Web-Ods-AdminApp/run.sh
> +envsubst < /app/appsettings.template.json > /app/temp.json
The idea is that we have the first occurrence of what will probably happen more over time: rather than ruthlessly plowing over the entire package-defined starting point for appsettings.json, we wanted to preserve a special value that's already carefully placed in the package (for google analytics), and we didn't want to commit it to source control redundantly here in this repo. So we still want to benefit from the envsubst idea for the most part, but needed multiple steps so we could ultimately combine the effects of envsubt and jq.

This actually makes me wonder whether more of this should be happening in the Dockerfile rather than here in run.

2021-04-27 21:18 UTC, saa14 commented on Web-Ods-AdminApp/run.sh
> +envsubst < /app/appsettings.template.json > /app/temp.json
The GA measurement ID subsitution code being in run.sh may not be an issue. When we run the container multiple times (stopping and restarting the container), we go through the commands in run.sh and still get the final appsettings.json with the correct GA Id and environment variables set.

2021-04-27 21:19 UTC, jamessmckay commented on Web-Ods-AdminApp/run.sh
> +envsubst < /app/appsettings.template.json > /app/temp.json
I have been experimenting with the builder patter in docker, and I see value in moving that way in the future. A lot of this work would move there and the script then would be just test to see if the db is up and running and if so, then start the application. Configuration that is done at build would be done during the build stage. The benefit is that the substitution would be built in a stage image that then would be discarded. and the final image would be as small as possible. However, if you have run time values, then you need to run it in a shell script and do an envstubst.

2021-04-27 21:21 UTC, jamessmckay approved these changes
some white space issues need to be updated, then we are good to go.

2021-04-27 21:21 UTC, jamessmckay commented on Web-Ods-AdminApp/Dockerfile
> +    wget -O /app/AdminApp.zip  https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_apis/packaging/feeds/EdFi/nuget/packages/EdFi.Suite3.ODS.AdminApp.Web/versions/${VERSION}/content && \
please fix white space
```suggestion
    wget -O /app/AdminApp.zip https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_apis/packaging/feeds/EdFi/nuget/packages/EdFi.Suite3.ODS.AdminApp.Web/versions/${VERSION}/content && \
```

2021-04-27 21:21 UTC, jamessmckay commented on Web-Ods-AdminApp/appsettings.template.json
> +      "LogLevel": {
please revert whitespace change

2021-04-28 12:41 UTC, jamessmckay approved these changes

2021-04-28 12:42 UTC, merged