Added Dockerfile
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #7
Opened 2020-10-26 06:31 UTC by smundheinnive

2020-10-26 09:03 UTC, ptar-innive commented on PSQL-Admin/Dockerfile
> +ADD https://ed-fi-alliance.slack.com/files/U8QTCGJSC/F01CRK4EU03/edfi_security.sql /docker-entrypoint-initdb.d/
please download this file into this folder, commit it, and use it from this folder

2020-10-26 09:03 UTC, ptar-innive commented on PSQL-Admin/Dockerfile
> +ADD https://ed-fi-alliance.slack.com/files/U8QTCGJSC/F01DF8DR9LG/edfi_admin.sql /docker-entrypoint-initdb.d/
please download this file into this folder, commit it, and use it from this folder

2020-10-26 14:11 UTC, smundheinnive commented on PSQL-Admin/Dockerfile
> +ADD https://ed-fi-alliance.slack.com/files/U8QTCGJSC/F01CRK4EU03/edfi_security.sql /docker-entrypoint-initdb.d/
@ptar-innive modified the dockerfile ,I should re-request review option?

2020-10-28 13:10 UTC, jamessmckay requested changes

2020-10-28 13:10 UTC, jamessmckay commented on PSQL-Admin/Dockerfile
> +#Need to copy *.sql files to "docker-entrypoint-initdb.d" from local machine otherwise getting errorr while copying files
```suggestion
#Need to copy *.sql files to "docker-entrypoint-initdb.d" from local machine otherwise getting error while copying files

```
```

2020-10-28 13:13 UTC, jamessmckay approved these changes

2020-10-28 13:14 UTC, merged