[AA-1248] Reconfigure Admin App to Access the API via NGiNX
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #74
Opened 2021-07-30 20:24 UTC by CSR2017

@stephenfuqua @vimayya 
Please help review and merge the changes. Thanks
1. Update nginx to allow just SSL port. 
2. Enable port 80 for ODS API for internal communication from Admin app container. 
3. Refactor API_INTERNAL and API_EXTERNAL urls formation on compose files.

2021-07-31 01:15 UTC, stephenfuqua commented
I do not have experience diagnosing Docker build failures, and the links above are strangely broken. There are only a few accounts that can access the builds, so I'm going to paste some build failure information below. This is the first time these builds have run in 3 months. I will also try running these on my computer, which is new and has never run been used with the Docker images yet.

The following error shows up in several builds. There are also builds that don't have postgresql but do have the error for unzip.

```
#11 [6/6] RUN apk --no-cache add unzip=6.0-r8 dos2unix=7.4.2-r0 bash=5.1.0-r0 gettext=0.20.2-r2 postgresql-client=13.2-r0 icu=67.1-r2 && wget -O /app/SandboxAdmin.zip https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_apis/packaging/feeds/EdFi/nuget/packages/EdFi.Suite3.Ods.SandboxAdmin/versions/5.2.14406/content && unzip /app/SandboxAdmin.zip -d /app && rm -f /app/SandboxAdmin.zip && rm -f /app/appsettings.json && cp /app/log4net.txt /app/log4net.config && dos2unix /app/*.json && dos2unix /app/*.sh && dos2unix /app/log4net.config && chmod 700 /app/run.sh && rm -f /app/*.exe
#11 sha256:0e7b7919393dccc919f7a2677ad9978a2a155c34fab8301d0fcb4ffeb0ae7eee
#11 0.507 fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
#11 0.607 fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
#11 0.881 ERROR: unable to select packages:
#11 0.922 postgresql-client-13.3-r0:
#11 0.922 breaks: world[postgresql-client=13.2-r0]
#11 0.922 unzip-6.0-r9:
#11 0.922 breaks: world[unzip=6.0-r8]
```

2021-07-31 02:12 UTC, stephenfuqua commented
The error appears to be occurring because the available version some packages is newer than the one we have specified in our Docker files. I've adjusted all of the Alpine package versions to look for the newest patch with a fix version of the major and minor. This resolves the same problem when I build on my localhost, but then I get a different error when trying to connect to Azure packages - so I've not been successful in building locally yet. Will see what happens on Docker. If those builds succeed then I can pull the images and test locally.

2021-07-31 03:36 UTC, stephenfuqua commented
The builds are clean and tagged as `pre-aa`. When I run locally the gateway is not responding. NGiNX is not reporting any errors or any access attempts. My changes might have been too aggressive. Will roll back part of the change and try something else ... but not this late on Friday evening.

2021-08-02 20:33 UTC, stephenfuqua reviewed
Overall looks good. I have one suggestion for improved documentation. I am not going to approve the PR - will leave that to the ODS Platform team.

2021-08-02 20:33 UTC, stephenfuqua commented on Web-Ods-AdminApp/Alpine/mssql/README.md
> +API_HOSTNAME value is required for successfully connecting to ODS/API.
```suggestion

`API_HOSTNAME` value is required for successfully connecting to ODS/API. This should be the full host (server) name for public access to the API, not including protocol (e.g. "https") or path (e.g. "/api"). For example, if running on a virtual machine called `edfi` on network `my-district.edu` then this value would be `API_HOSTNAME=edfi.my-district.edu`.
```

2021-08-03 21:22 UTC, blmeyers requested changes

2021-08-03 21:22 UTC, blmeyers commented on Web-Gateway/Alpine/default.conf.template
> +}
This part I'm unsure of.  Why are we opening up access through nginx on port 80 for just the ODS/API, vs the original code which automatically redirected any http traffic to https? You also removed the port mapping for 80 on the compose files, which was used to allow access in on http/80, and then redirect them to https.  Is this something necessary to make Admin App integration work?

2021-08-04 14:10 UTC, CSR2017 commented on Web-Gateway/Alpine/default.conf.template
> +}
@blmeyers 
Yes, we need to expose ODS API on port 80 for Admin App integration internally via nginx. To allow port 80, get to remove the redirection server section from default.conf.template file. This will allow ODS API to be accessible on port 80 from outside. So, for avoiding that we removed port 80 from nginx section on compose file!!

2021-08-04 23:02 UTC, stephenfuqua commented on Web-Gateway/Alpine/default.conf.template
> +}
Now that I've been able to step back from this work and think about it more, I see another problem, although it is not insurmountable: If someone sets up load balancing on the API, they'll likely do that in the 443 configuration and forget to do it in the port 80 configuration. Then the Admin App will still be accessing just a single container instead of the load balanced container.

When I wrote the ticket, I was envisioning a single `server` entry with both port 80 and 443. But I did not, at that time, think about the headers that are being set, and the HTTP redirect.

Personally, I have no hesitation about having port 80 turned on inside the Docker network without forcing redirection. Just don't expose that to the outside world. Similarly we're not enforcing encrypted connections to the database inside of the container, and I see this as directly analogous. And I don't have any concern about the whole redirect thing. Just don't allow traffic in to port 80. But maybe there's something important I don't know here about real world access - out in the field, are there vendors who keep trying to use HTTP instead of HTTPS?

But this redirect discussion is a bit immaterial, because our current solution isn't satisfactory in the end - since it requires setting up duplicate load balancing in both `server` sections of the configuration file.

I still think we need to find a way for the Admin App to access a load balanced server, and that means it should go ahead and access port 443. In the ticket I said that TLS is not _required_, but it is not forbidden either. Is it possible to just have Admin App use `API_INTERNAL_URL: 'https://nginx/${ODS_VIRTUAL_NAME}'` (note httpS not http)? Is there any certificate trust issue with doing so?

2021-08-10 14:11 UTC, blmeyers requested changes

2021-08-10 14:11 UTC, blmeyers commented on Compose/mssql/compose-shared-instance-env-build.yml
> +      - ../../Web-Gateway/ssl:/ssl/
Shouldn't this be "../../ssl:ssl/" similar to how the compose file for nginx is setup?

2021-08-10 14:11 UTC, blmeyers commented on Web-Ods-AdminApp/Alpine/mssql/run.sh
> +cp /ssl/server.* /usr/local/share/ca-certificates/
If we're just going to copy the cert anyways, why not do this as part of the docker file?  Right now you're requiring them to mount the cert to a volume (and requiring us to maintain that on every compose) and then you're only using it to copy in.  Also do we actually need to copy the private key file over for trust, or can we only copy the public certificate to keep the private key better protected?

2021-08-10 14:11 UTC, blmeyers commented on Compose/mssql/compose-shared-instance-env-build.yml
> +      - ../../Web-Gateway/ssl:/ssl/
Or see my comment below, maybe we shouldn't even be adding this.

2021-08-10 14:11 UTC, blmeyers commented on generate-cert.sh
> +openssl req -subj '/CN=localhost' -x509 -newkey rsa:4096 -nodes -keyout ssl/server.key -out ssl/server.crt -days 365 -addext "subjectAltName = DNS:nginx"
There will need to be doc updates to clarify that the cert used needs to have a SubjectAltName for nginx in order to work with Admin App, since that wouldn't be expected if the user was acquiring a cert outside of self signed.  Probably a separate ticket for those updates?

2021-08-10 14:55 UTC, CSR2017 commented on Compose/mssql/compose-shared-instance-env-build.yml
> +      - ../../Web-Gateway/ssl:/ssl/
> Shouldn't this be "../../ssl:ssl/" similar to how the compose file for nginx is setup?

Yes, agree. I had that ssl folder on root level as well as inside the Web-Gateway folder. Will change to pointing to root level ssl folder

2021-08-10 21:23 UTC, blmeyers approved these changes

2021-08-11 15:40 UTC, merged