[ODS-5038] Resolve build errors caused by dependence on outdated packages
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker pull request #78
Opened 2021-08-02 20:20 UTC by stephenfuqua

I have tested the Admin App / API integration with tag pre-aa. I am unable to build the images locally because I get an error when downloading packages from Azure; appears to be problem with my Internet connection provider, as it occurs on both my work and home computers. The pre-aa build process does not cover the Sandbox components, so I have not been able to test them. Someone who can build locally should startup the sandbox environment from this branch to confirm that everything is working.

2021-08-02 21:26 UTC, blmeyers requested changes
Tested locally with both sandbox and shared setup, primarily around the ODS/API portion.

2021-08-02 21:30 UTC, stephenfuqua commented on Web-Ods-AdminApp/Alpine/mssql/Dockerfile
> +RUN apk --no-cache add unzip=~6.0 dos2unix=~7.4 bash=~5.1 gettext=~0.20 postgresql-client=~13.3 jq=~1.6 icu=~67.1 && \
I had an error message indicating that 13.3 is the currently available version, which is confirmed at https://pkgs.alpinelinux.org/packages?name=postgresql-client&branch=edge. To be honest, I don't even like the fact that we're using 13 instead of 11, but I don't know enough about Alpine to know how to avoid that.

2021-08-03 00:04 UTC, vimayya commented
@blmeyers All good on testing. Is @stephenfuqua's explanation on postgresql client version address your concern? Are we good to merge?

2021-08-03 14:07 UTC, blmeyers commented on Web-Ods-AdminApp/Alpine/mssql/Dockerfile
> +RUN apk --no-cache add unzip=~6.0 dos2unix=~7.4 bash=~5.1 gettext=~0.20 postgresql-client=~13.3 jq=~1.6 icu=~67.1 && \
Yep makes sense, probably worth spinning another ticket on our side to go take a pass and make sure everything is updated to latest.

2021-08-03 14:07 UTC, blmeyers approved these changes

2021-08-03 14:10 UTC, merged